### ISSUE TITLE
Hi here is a `.pre-commit-config.yaml` hope can help you. (zyp yyds!)

### ISSUE THREAD

**Issue by Lucareful** [hansomefish/go-playground#3]
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    # - id: go-vet
    - id: go-lint
    - id: go-imports
    # - id: go-cyclo
      # args: [-over=15]
    - id: validate-toml
    # - id: no-go-testing
    - id: golangci-lint
    # - id: go-critic
    # - id: go-unit-tests
    # - id: go-build
    - id: go-mod-tidy

- repo: local
  hooks:
    - id: go-vet
      name: go-vet
      language: system
      entry: ./run-go-vet.sh
```

```shell
# run-go-vet.sh 

#!/usr/bin/env bash
set -e
pkg=$(go list -m)
for dir in $(echo $@|xargs -n1 dirname|sort -u); do
  go vet $pkg/$dir
done
```
